name: build

on:
  workflow_dispatch: # سيتم البناء فقط عند التشغيل اليدوي من واجهة GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      uses: ./.github/workflows/build
